// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/espitman/gws-chat/message-service/internal/adapter/database/postgres/ent/predicate"
	"github.com/espitman/gws-chat/message-service/internal/adapter/database/postgres/ent/room"
)

// RoomUpdate is the builder for updating Room entities.
type RoomUpdate struct {
	config
	hooks     []Hook
	mutation  *RoomMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RoomUpdate builder.
func (ru *RoomUpdate) Where(ps ...predicate.Room) *RoomUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetRoomID sets the "RoomID" field.
func (ru *RoomUpdate) SetRoomID(s string) *RoomUpdate {
	ru.mutation.SetRoomID(s)
	return ru
}

// SetNillableRoomID sets the "RoomID" field if the given value is not nil.
func (ru *RoomUpdate) SetNillableRoomID(s *string) *RoomUpdate {
	if s != nil {
		ru.SetRoomID(*s)
	}
	return ru
}

// SetUsers sets the "Users" field.
func (ru *RoomUpdate) SetUsers(s string) *RoomUpdate {
	ru.mutation.SetUsers(s)
	return ru
}

// SetNillableUsers sets the "Users" field if the given value is not nil.
func (ru *RoomUpdate) SetNillableUsers(s *string) *RoomUpdate {
	if s != nil {
		ru.SetUsers(*s)
	}
	return ru
}

// Mutation returns the RoomMutation object of the builder.
func (ru *RoomUpdate) Mutation() *RoomMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RoomUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RoomUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RoomUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RoomUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ru *RoomUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RoomUpdate {
	ru.modifiers = append(ru.modifiers, modifiers...)
	return ru
}

func (ru *RoomUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(room.Table, room.Columns, sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.RoomID(); ok {
		_spec.SetField(room.FieldRoomID, field.TypeString, value)
	}
	if value, ok := ru.mutation.Users(); ok {
		_spec.SetField(room.FieldUsers, field.TypeString, value)
	}
	_spec.AddModifiers(ru.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RoomUpdateOne is the builder for updating a single Room entity.
type RoomUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RoomMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetRoomID sets the "RoomID" field.
func (ruo *RoomUpdateOne) SetRoomID(s string) *RoomUpdateOne {
	ruo.mutation.SetRoomID(s)
	return ruo
}

// SetNillableRoomID sets the "RoomID" field if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableRoomID(s *string) *RoomUpdateOne {
	if s != nil {
		ruo.SetRoomID(*s)
	}
	return ruo
}

// SetUsers sets the "Users" field.
func (ruo *RoomUpdateOne) SetUsers(s string) *RoomUpdateOne {
	ruo.mutation.SetUsers(s)
	return ruo
}

// SetNillableUsers sets the "Users" field if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableUsers(s *string) *RoomUpdateOne {
	if s != nil {
		ruo.SetUsers(*s)
	}
	return ruo
}

// Mutation returns the RoomMutation object of the builder.
func (ruo *RoomUpdateOne) Mutation() *RoomMutation {
	return ruo.mutation
}

// Where appends a list predicates to the RoomUpdate builder.
func (ruo *RoomUpdateOne) Where(ps ...predicate.Room) *RoomUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RoomUpdateOne) Select(field string, fields ...string) *RoomUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Room entity.
func (ruo *RoomUpdateOne) Save(ctx context.Context) (*Room, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RoomUpdateOne) SaveX(ctx context.Context) *Room {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RoomUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RoomUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ruo *RoomUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RoomUpdateOne {
	ruo.modifiers = append(ruo.modifiers, modifiers...)
	return ruo
}

func (ruo *RoomUpdateOne) sqlSave(ctx context.Context) (_node *Room, err error) {
	_spec := sqlgraph.NewUpdateSpec(room.Table, room.Columns, sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Room.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, room.FieldID)
		for _, f := range fields {
			if !room.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != room.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.RoomID(); ok {
		_spec.SetField(room.FieldRoomID, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Users(); ok {
		_spec.SetField(room.FieldUsers, field.TypeString, value)
	}
	_spec.AddModifiers(ruo.modifiers...)
	_node = &Room{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
