// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: proto/user-service/request.proto

package user_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type V1LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty" validate:"required"`         // @gotags: validate:"required"
	Password string `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty" validate:"required"` // @gotags: validate:"required"
}

func (x *V1LoginRequest) Reset() {
	*x = V1LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_service_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V1LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1LoginRequest) ProtoMessage() {}

func (x *V1LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1LoginRequest.ProtoReflect.Descriptor instead.
func (*V1LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{0}
}

func (x *V1LoginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *V1LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type V1GetAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Me bool `protobuf:"varint,1,opt,name=me,proto3" json:"me,omitempty" validate:"boolean"` // @gotags: validate:"boolean"
}

func (x *V1GetAllRequest) Reset() {
	*x = V1GetAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_service_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V1GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1GetAllRequest) ProtoMessage() {}

func (x *V1GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1GetAllRequest.ProtoReflect.Descriptor instead.
func (*V1GetAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{1}
}

func (x *V1GetAllRequest) GetMe() bool {
	if x != nil {
		return x.Me
	}
	return false
}

type V1ValidateTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty" validate:"required"` // @gotags: validate:"required"
}

func (x *V1ValidateTokenRequest) Reset() {
	*x = V1ValidateTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_service_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V1ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1ValidateTokenRequest) ProtoMessage() {}

func (x *V1ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*V1ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{2}
}

func (x *V1ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type V1GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint32 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty" validate:"required"` // @gotags: validate:"required"
}

func (x *V1GetRequest) Reset() {
	*x = V1GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_service_request_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V1GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1GetRequest) ProtoMessage() {}

func (x *V1GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1GetRequest.ProtoReflect.Descriptor instead.
func (*V1GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{3}
}

func (x *V1GetRequest) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type V1GetByIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIDs []uint32 `protobuf:"varint,1,rep,packed,name=UserIDs,proto3" json:"UserIDs,omitempty" validate:"required"` // @gotags: validate:"required"
}

func (x *V1GetByIDsRequest) Reset() {
	*x = V1GetByIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_service_request_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V1GetByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1GetByIDsRequest) ProtoMessage() {}

func (x *V1GetByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1GetByIDsRequest.ProtoReflect.Descriptor instead.
func (*V1GetByIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{4}
}

func (x *V1GetByIDsRequest) GetUserIDs() []uint32 {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

type V1SetOnlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   uint32 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty" validate:"required"`    // @gotags: validate:"required"
	IsOnline bool   `protobuf:"varint,2,opt,name=IsOnline,proto3" json:"IsOnline,omitempty" validate:"boolean"` // @gotags: validate:"boolean"
}

func (x *V1SetOnlineRequest) Reset() {
	*x = V1SetOnlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_service_request_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V1SetOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1SetOnlineRequest) ProtoMessage() {}

func (x *V1SetOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1SetOnlineRequest.ProtoReflect.Descriptor instead.
func (*V1SetOnlineRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{5}
}

func (x *V1SetOnlineRequest) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *V1SetOnlineRequest) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

var File_proto_user_service_request_proto protoreflect.FileDescriptor

var file_proto_user_service_request_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x0e, 0x56, 0x31, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x21, 0x0a, 0x0f, 0x56,
	0x31, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6d, 0x65, 0x22, 0x2e,
	0x0a, 0x16, 0x56, 0x31, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x26,
	0x0a, 0x0c, 0x56, 0x31, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x2d, 0x0a, 0x11, 0x56, 0x31, 0x47, 0x65, 0x74, 0x42,
	0x79, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x73, 0x22, 0x48, 0x0a, 0x12, 0x56, 0x31, 0x53, 0x65, 0x74, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42,
	0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x73,
	0x70, 0x69, 0x74, 0x6d, 0x61, 0x6e, 0x2f, 0x67, 0x77, 0x73, 0x2d, 0x63, 0x68, 0x61, 0x74, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x67, 0x65, 0x6e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_user_service_request_proto_rawDescOnce sync.Once
	file_proto_user_service_request_proto_rawDescData = file_proto_user_service_request_proto_rawDesc
)

func file_proto_user_service_request_proto_rawDescGZIP() []byte {
	file_proto_user_service_request_proto_rawDescOnce.Do(func() {
		file_proto_user_service_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_user_service_request_proto_rawDescData)
	})
	return file_proto_user_service_request_proto_rawDescData
}

var file_proto_user_service_request_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_user_service_request_proto_goTypes = []interface{}{
	(*V1LoginRequest)(nil),         // 0: proto.V1LoginRequest
	(*V1GetAllRequest)(nil),        // 1: proto.V1GetAllRequest
	(*V1ValidateTokenRequest)(nil), // 2: proto.V1ValidateTokenRequest
	(*V1GetRequest)(nil),           // 3: proto.V1GetRequest
	(*V1GetByIDsRequest)(nil),      // 4: proto.V1GetByIDsRequest
	(*V1SetOnlineRequest)(nil),     // 5: proto.V1SetOnlineRequest
}
var file_proto_user_service_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_service_request_proto_init() }
func file_proto_user_service_request_proto_init() {
	if File_proto_user_service_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_user_service_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V1LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_service_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V1GetAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_service_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V1ValidateTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_service_request_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V1GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_service_request_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V1GetByIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_service_request_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V1SetOnlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_user_service_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_service_request_proto_goTypes,
		DependencyIndexes: file_proto_user_service_request_proto_depIdxs,
		MessageInfos:      file_proto_user_service_request_proto_msgTypes,
	}.Build()
	File_proto_user_service_request_proto = out.File
	file_proto_user_service_request_proto_rawDesc = nil
	file_proto_user_service_request_proto_goTypes = nil
	file_proto_user_service_request_proto_depIdxs = nil
}
