// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/espitman/gws-chat/user-service/internal/adapter/database/postgres/ent/schema"
	"github.com/espitman/gws-chat/user-service/internal/adapter/database/postgres/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAvatar is the schema descriptor for Avatar field.
	userDescAvatar := userFields[2].Descriptor()
	// user.DefaultAvatar holds the default value on creation for the Avatar field.
	user.DefaultAvatar = userDescAvatar.Default.(string)
	// userDescStatus is the schema descriptor for Status field.
	userDescStatus := userFields[3].Descriptor()
	// user.DefaultStatus holds the default value on creation for the Status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// userDescIsOnline is the schema descriptor for IsOnline field.
	userDescIsOnline := userFields[4].Descriptor()
	// user.DefaultIsOnline holds the default value on creation for the IsOnline field.
	user.DefaultIsOnline = userDescIsOnline.Default.(bool)
}
