// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChatRoomsMembersColumns holds the columns for the "chat_rooms_members" table.
	ChatRoomsMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "room_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeUint32},
	}
	// ChatRoomsMembersTable holds the schema information for the "chat_rooms_members" table.
	ChatRoomsMembersTable = &schema.Table{
		Name:       "chat_rooms_members",
		Columns:    ChatRoomsMembersColumns,
		PrimaryKey: []*schema.Column{ChatRoomsMembersColumns[0]},
	}
	// ChatRoomsColumns holds the columns for the "chat_rooms" table.
	ChatRoomsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "room_id", Type: field.TypeString},
		{Name: "users", Type: field.TypeString, Unique: true},
	}
	// ChatRoomsTable holds the schema information for the "chat_rooms" table.
	ChatRoomsTable = &schema.Table{
		Name:       "chat_rooms",
		Columns:    ChatRoomsColumns,
		PrimaryKey: []*schema.Column{ChatRoomsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChatRoomsMembersTable,
		ChatRoomsTable,
	}
)

func init() {
	ChatRoomsMembersTable.Annotation = &entsql.Annotation{
		Table: "chat_rooms_members",
	}
	ChatRoomsTable.Annotation = &entsql.Annotation{
		Table: "chat_rooms",
	}
}
