// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Member is the predicate function for member builders.
type Member func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)
